export const heroInformation = {
  title1: 'SOMOS SOCIOS',
  title2: 'COMPROMETIDOS',
  text: 'Valoramos enormemente las relaciones sólidas y hemos visto los beneficios que aportan a nuestro negocio. La retroalimentación de los clientes es vital para ayudarnos a hacerlo bien.',
  backgroundImage: 'assets/heroTestimonios.png',
};

export const ListaTestimonios = [
  {
    image: 'assets/IsabelCumbres.png',
    workshop: 'AUTOCRAFT',
    text: '“Radar es una herramienta indispensable para todo centro de reparación automotriz de alta productividad. Es muy intuitiva, y genera información valiosa para la correcta planeación de los procesos de reparación y para el preciso servicio al cliente”.',
    name: 'Mario Correa Canto',
    position: 'Dueño de taller',
    image2: 'assets/IsabelCumbres',
    location: 'Mérida, Yucatán',
  },
  {
    image: 'assets/DanielaOrtiz.png',
    workshop: 'ETAPEL',
    text: '“Nuestra franquicia maneja altos estándares de calidad y un excelente servicio, por lo que buscábamos un aliado para la gestión del taller que estuviera a la vanguardia en la industria y nos permitiera seguir de cerca cada movimiento operativo y financiero. Afortunadamente conocimos a Radar que ha sido el complemento perfecto para nuestro modelo de negocios.”',
    name: 'Daniela Ortiz',
    position: 'Dirección',
    image2: 'assets/DanielaOrtiz',
    location: 'CDMX',
  },
  {
    image: 'assets/IsabelCumbres.png',
    workshop: 'VW CUMBRES',
    text: '"Radar... Es nuestra herramienta de confianza. Con la cual podemos llevar a cabo todo el proceso de Carrocería y Pintura. Tiene las cualidades que todo sistema requiere: Es confiable, ágil, óptimo, práctico y, lo mejor es que está al alcance de todas las personas que se involucran en el proceso."',
    name: 'Isabel Barrera Orihuela',
    position: 'RAD',
    image2: 'assets/IsabelCumbres',
    location: 'Cancún, Quintana Roo',
  },
  {
    image: 'assets/Yoichi.png',
    workshop: 'LAMINAUTOS',
    text: '“Es una excelente herramienta para administrar el taller de forma integral. Brinda información en tiempo real y relevante de cada proceso de tal forma que cada usuario puede enfocarse su trabajo para contribuir en el resultado colectivo.”',
    name: 'Yoichi Nagatome',
    position: 'Dirección de taller',
    image2: 'assets/Yoichi',
    location: 'León, Gto',
  },
  {
    image: 'assets/WalterArcusin-Testimonio.png',
    workshop: 'Programa MVP',
    text: '"Una herramienta ágil, intuitiva y completa con la que se puede controlar y medir todo el proceso de un CDR desde la recepción hasta la entrega de los vehículos, asegurando la interacción con los clientes, proveedores y aseguradoras."',
    name: 'Walter Arcusin',
    position: 'Consultor PPG',
    image2: 'assets/WalterArcusin',
    location: 'Guadalajara, Jalisco',
  },
  {
    image: 'assets/Irazu.png',
    workshop: 'VW KOLBEN',
    text: '"RADAR en comparativa al sistema anterior que teníamos es más práctico de usar, puedes medir en tiempo real tu unidad, es un sistema más amigable para nuestros clientes porque los puedes contactar de manera visual por medio de su integración con WhatsApp, me ha ayudado a generar reportes y dejar Excel, puedes ver el taller y sus fallas mediante los Dashboards sin necesidad de trasladarte al taller y las fotos las subes al instante de manera súper práctica."',
    name: 'Irazú González',
    position: 'Asesora de HyP',
    image2: 'assets/Irazu',
    location: 'León, Gto',
  },
  {
    image: 'assets/JohnsonVite.png',
    workshop: 'VW PACHUCA',
    text: '“RADAR es una plataforma que nos ha ayudado a tener mejor comunicación tanto interna como con nuestros clientes, nos ha facilitado medir todos los procesos del CDR y ahora llevamos un mejor control de cada uno de ellos, considero que es una herramienta muy útil dentro de mi CDR."',
    name: 'Jhonson Vite',
    position: 'Jefe de Taller',
    image2: 'assets/JohnsonVite',
    location: 'Pachuca, Hidalgo',
  },      
  {
    image: 'assets/MarcoEspinosa-Testimonio.png',
    workshop: 'VOLKSWAGEN Y SEAT POTOSINA',
    text: '"RADAR me ayuda a hacer mi planeación diaria, me dice donde enfocar mis esfuerzos, desde la carga de trabajo por operario, asignar la nómina, hasta detectar autos con problemas para dar solución oportuna."',
    name: 'Marco Espinosa',
    position: 'Jefe de taller',
    first: true,
    image2: 'assets/MarcoEspinosa',
    location: 'San Luis Potosí, San Luis Potosí',
  },
  {
    image: 'assets/MauricioHerrera-Testimonio.png',
    workshop: 'VW RAFEDHER',
    text: '"Radar es control a tu alcance."',
    name: 'Mauricio Herrera',
    position: 'Director',
    image2: 'assets/MauricioHerrera',
    location: 'Aguascalientes, Ags',
  },  
];
